/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_a14c7986 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/opmvuhlheenygwbqwljk/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "@supabase/supabase-js";

type KvRow<T> = {
  key: string;
  value: T;
};

const getSupabaseClient = () => {
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseServiceRoleKey) {
    throw new Error("Supabase credentials are not configured in the environment");
  }

  return createClient(supabaseUrl, supabaseServiceRoleKey);
};

// Set stores a key-value pair in the database.
export async function set<T>(key: string, value: T): Promise<void> {
  const supabase = getSupabaseClient();
  const { error } = await supabase.from("kv_store_a14c7986").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
}

// Get retrieves a key-value pair from the database.
export async function get<T>(key: string): Promise<T | null> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("kv_store_a14c7986")
    .select("value")
    .eq("key", key)
    .maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  const row = (data as KvRow<T> | null) ?? null;
  return row?.value ?? null;
}

// Delete deletes a key-value pair from the database.
export async function del(key: string): Promise<void> {
  const supabase = getSupabaseClient();
  const { error } = await supabase.from("kv_store_a14c7986").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
}

// Sets multiple key-value pairs in the database.
export async function mset<T>(keys: string[], values: T[]): Promise<void> {
  const supabase = getSupabaseClient();
  const { error } = await supabase.from("kv_store_a14c7986").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
}

// Gets multiple key-value pairs from the database.
export async function mget<T>(keys: string[]): Promise<T[]> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("kv_store_a14c7986")
    .select("value")
    .in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  const rows = (data as KvRow<T>[] | null) ?? [];
  return rows.flatMap((row) => (row.value === undefined ? [] : [row.value]));
}

// Deletes multiple key-value pairs from the database.
export async function mdel(keys: string[]): Promise<void> {
  const supabase = getSupabaseClient();
  const { error } = await supabase.from("kv_store_a14c7986").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
}

// Search for key-value pairs by prefix.
export async function getByPrefix<T>(prefix: string): Promise<T[]> {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase
    .from("kv_store_a14c7986")
    .select("key, value")
    .like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  const rows = (data as KvRow<T>[] | null) ?? [];
  return rows.flatMap((row) => (row.value === undefined ? [] : [row.value]));
}
